---
- name: Install bird
  apt:
    pkg: "{{item}}"
    update_cache: yes
    state: present
  with_items:
    - bird
  register: apt_bird

- name: Set bird to atomatic start on system startup
  shell: systemctl enable bird.service
  when: "apt_bird.changed and ansible_distribution_release == 'jessie' or ansible_distribution_release == 'xenial'"

- name: configure bird.conf
  template: src=bird.conf.j2 dest=/etc/bird/bird.conf
  notify:
   - configure bird

- name: bird aktivieren und starten
  service: name=bird state=started enabled=yes

- name: Execute all triggered handlers
  meta: flush_handlers
